# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'extractfileui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(662, 375)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.chooseDirButton = QtWidgets.QPushButton(self.centralwidget)
        self.chooseDirButton.setGeometry(QtCore.QRect(200, 10, 93, 28))
        self.chooseDirButton.setObjectName("chooseDirButton")
        self.ProjectList = QtWidgets.QListWidget(self.centralwidget)
        self.ProjectList.setGeometry(QtCore.QRect(30, 40, 256, 192))
        self.ProjectList.setObjectName("ProjectList")
        self.fileList = QtWidgets.QListWidget(self.centralwidget)
        self.fileList.setGeometry(QtCore.QRect(365, 40, 261, 192))
        self.fileList.setObjectName("fileList")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(50, 240, 451, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.saveDirShow = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.saveDirShow.setText("")
        self.saveDirShow.setObjectName("saveDirShow")
        self.horizontalLayout.addWidget(self.saveDirShow)
        self.getSaveDirButton = QtWidgets.QPushButton(self.centralwidget)
        self.getSaveDirButton.setGeometry(QtCore.QRect(530, 240, 81, 28))
        self.getSaveDirButton.setMaximumSize(QtCore.QSize(1777215, 16777215))
        self.getSaveDirButton.setObjectName("getSaveDirButton")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 10, 72, 15))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(370, 20, 72, 15))
        self.label_4.setObjectName("label_4")
        self.updateFileButton = QtWidgets.QPushButton(self.centralwidget)
        self.updateFileButton.setGeometry(QtCore.QRect(300, 120, 51, 28))
        self.updateFileButton.setObjectName("updateFileButton")
        self.extractButton = QtWidgets.QPushButton(self.centralwidget)
        self.extractButton.setGeometry(QtCore.QRect(530, 300, 93, 28))
        self.extractButton.setObjectName("extractButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 662, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.chooseDirButton.setText(_translate("MainWindow", "Choose Dir"))
        self.label_2.setText(_translate("MainWindow", "Save Dir:"))
        self.getSaveDirButton.setText(_translate("MainWindow", "..."))
        self.label_3.setText(_translate("MainWindow", "Project"))
        self.label_4.setText(_translate("MainWindow", "File"))
        self.updateFileButton.setText(_translate("MainWindow", "Update"))
        self.extractButton.setText(_translate("MainWindow", "Extract"))
        self.menu.setTitle(_translate("MainWindow", "批量提取文件"))
