# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'extractfileui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(662, 375)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.chooseDirButton = QtWidgets.QPushButton(self.centralwidget)
        self.chooseDirButton.setGeometry(QtCore.QRect(190, 10, 93, 28))
        self.chooseDirButton.setObjectName("chooseDirButton")
        self.ProjectList = QtWidgets.QListWidget(self.centralwidget)
        self.ProjectList.setGeometry(QtCore.QRect(30, 40, 250, 190))
        self.ProjectList.setObjectName("ProjectList")
        self.fileList = QtWidgets.QListWidget(self.centralwidget)
        self.fileList.setGeometry(QtCore.QRect(365, 40, 250, 190))
        self.fileList.setObjectName("fileList")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(50, 240, 451, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.saveDirShow = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.saveDirShow.setText("")
        self.saveDirShow.setObjectName("saveDirShow")
        self.horizontalLayout.addWidget(self.saveDirShow)
        self.getSaveDirButton = QtWidgets.QPushButton(self.centralwidget)
        self.getSaveDirButton.setGeometry(QtCore.QRect(530, 240, 81, 28))
        self.getSaveDirButton.setMaximumSize(QtCore.QSize(1777215, 16777215))
        self.getSaveDirButton.setObjectName("getSaveDirButton")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 10, 72, 15))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(370, 10, 72, 15))
        self.label_4.setObjectName("label_4")
        self.updateFileButton = QtWidgets.QPushButton(self.centralwidget)
        self.updateFileButton.setGeometry(QtCore.QRect(290, 120, 71, 28))
        self.updateFileButton.setObjectName("updateFileButton")
        self.extractButton = QtWidgets.QPushButton(self.centralwidget)
        self.extractButton.setGeometry(QtCore.QRect(530, 280, 93, 28))
        self.extractButton.setObjectName("extractButton")
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 662, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "批量提取文件"))
        self.chooseDirButton.setText(_translate("mainWindow", "Choose Dir"))
        self.label_2.setText(_translate("mainWindow", "Save Dir:"))
        self.getSaveDirButton.setText(_translate("mainWindow", "..."))
        self.label_3.setText(_translate("mainWindow", "Project"))
        self.label_4.setText(_translate("mainWindow", "File"))
        self.updateFileButton.setText(_translate("mainWindow", "Update"))
        self.extractButton.setText(_translate("mainWindow", "Extract"))
        self.menu.setTitle(_translate("mainWindow", "批量提取文件"))
